WebAppMVC/WebAppMVC/Models/Category.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace WebAppMVC.Models
{
    public class Category
    {
        public int CategoryId { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public string IconFilename { get; set; }

        public virtual ICollection<Product> Products { get; set; }
    }
}

WebAppMVC/WebAppMVC/Models/Order.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace WebAppMVC.Models
{
    public class Order
    {
        public int OrderId { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Address { get; set; }
        public string CodeAndCity { get; set; }
        public string PhoneNumber { get; set; }
        public string Email { get; set; }

        public string Comment { get; set; }
        public DateTime DateCreated { get; set; }
        public OrderState OrderState { get; set; }

        public decimal TotalPrice { get; set; }

        public List<OrderItem> OrderItems { get; set; }
    }

    public enum OrderState
    {
        New,
        Shipped,
        Canceled
    }
}

WebAppMVC/WebAppMVC/Models/OrderItem.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace WebAppMVC.Models
{
    public class OrderItem
    {
        public int OrderItemId { get; set; }
        public int Quantity { get; set; }
        public decimal UnitPrice { get; set; }

        public int ProductId { get; set; }
        public virtual Product Product { get; set; }

        public int OrderId { get; set; }
        public virtual Order Order { get; set; }

    }
}

WebAppMVC/WebAppMVC/Models/Product.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace WebAppMVC.Models
{
    public class Product
    {
        public int ProductId { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public DateTime DateAdded { get; set; }
        public string ImageFileName { get; set; }
        public decimal Price { get; set; }
        public bool IsBestPrice { get; set; }
        public bool IsHidden { get; set; }

        public int CategoryId { get; set; }
        public virtual Category Category { get; set; }
    }
}

WebAppMVC/WebAppMVC/ViewModels/HomeViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using WebAppMVC.Models;

namespace WebAppMVC.ViewModels
{
    public class HomeViewModel
    {
        public IEnumerable<Category> Categories { get; set; } 
        public IEnumerable<Product> BestProducts { get; set; } 
        public IEnumerable<Product> NewProducts { get; set; }
    }
}

WebAppMVC/WebAppMVC/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Data.Entity.Infrastructure;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebAppMVC.EntityDB;
using WebAppMVC.Models;
using WebAppMVC.ViewModels;

namespace WebAppMVC.Controllers
{
    public class HomeController : Controller
    {
        private StoreContext _db = new StoreContext();
        public ActionResult Index()
        {
            var categories = _db.Categories;
            var newProducts = _db.Products.Where(a => !a.IsHidden).OrderBy(a => a.DateAdded).Take(3).ToList();
            var bestProducts = _db.Products.Where(a => !a.IsHidden && a.IsBestPrice).OrderBy(g => Guid.NewGuid()).Take(3). ToList();
            var homeViewModel = new HomeViewModel
            {
                Categories = categories,
                NewProducts = newProducts,
                BestProducts = bestProducts
            };
            return View(homeViewModel);
        }
        public ActionResult StaticContent(string viewname)
        {
            return View(viewname);
        }
    }
}

WebAppMVC/WebAppMVC/Controllers/StoreController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace WebAppMVC.Controllers
{
    public class StoreController : Controller
    {
        // GET: Store
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult Details(int id)
        {
            return View();
        }

        public ActionResult List(string categoryName)
        {
            return View();
        }
    }
}

WebAppMVC/WebAppMVC/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
    Layout = "~/Views/_Layout.cshtml";
}

<h2>About</h2>

WebAppMVC/WebAppMVC/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
    Layout = "~/Views/_Layout.cshtml";
}

<h2>Contact</h2>

WebAppMVC/WebAppMVC/Views/Home/Index.cshtml
@using WebAppMVC.Infrastructure
@model WebAppMVC.ViewModels.HomeViewModel
@{
    Layout = "~/Views/_Layout.cshtml";
    ViewBag.Title = "Main page";
}
<nav class="genres-horizontal">
    <ul>
        @foreach (var category in Model.Categories)
        {
            <li>
                <a href="@Url.Action("List", "Store", new {categoryName = category.Name.ToLower()})"
                   style="background-image: url(@Url.CategoriesIconPath(category.IconFilename));">
                    @category.Name

                </a>
            </li>
        }
    </ul>
</nav>
<section>
    <ul class="ThreeColumnsCoversList large-cover-list">
        @foreach (var bestProduct in Model.BestProducts)
        { 
            <li>
                <article>
                    <a class="addtocartlink" href="aaaa">
                        <img src="../Content/Images/Site/cart.png" />
                    </a>
                    <a class="productdetailslink" href="@Url.Action("Details", "Store", new {id = bestProduct.ProductId})">
                        <div class="bestsellerFlag"></div>
                        <img class="album-cover" src="@Url.PhotosPath(bestProduct.ImageFileName)" />
                        <h1>
                            @bestProduct.Name
                        </h1>
                    </a>
                </article>
            </li>
        }
    </ul>
</section>
<section>
    <ul class="ThreeColumnsCoversList large-cover-list">
        @foreach (var newProduct in Model.NewProducts)
        {
            <li>
                <article>
                    <a class="addtocartlink" href="aaaa">
                        <img src="../Content/Images/Site/cart.png" />
                    </a>
                    <a class="productdetailslink" href="@Url.Action("Details", "Store", new {id = newProduct.ProductId})">
                        <div class="newFlag"></div>
                        <img class="album-cover" src="@Url.PhotosPath(newProduct.ImageFileName)" />
                        <h1>
                            @newProduct.Name
                        </h1>
                    </a>
                </article>
            </li>
        }
    </ul>
</section>



        @*@<ul class="ThreeColumnsCoversList large-cover-list">
                        <li>
                            <article>
                                <a class="addtocartlink" href="aaaa">
                                    <img src="../Content/Images/Site/cart.png" />
                                </a>
                                <a class="productdetailslink" href="asd">
                                    <div class="newFlag"></div>
                                    <img class="album-cover" src="../Content/Images/Photos/1.png" />
                                    <h1>
                                        Testowy obrazek
                                    </h1>
                                </a>
                            </article>
                        </li>
                        <li>
                            <article>
                                <a class="addtocartlink" href="aaaa">
                                    <img src="../Content/Images/Site/cart.png" />
                                </a>
                                <a class="productdetailslink" href="asd">
                                    <div class="newFlag"></div>
                                    <img class="album-cover" src="../Content/Images/Photos/2.png" />
                                    <h1>
                                        Testowy obrazek
                                    </h1>
                                </a>
                            </article>
                        </li>
                        <li>
                            <article>
                                <a class="addtocartlink" href="aaaa">
                                    <img src="../Content/Images/Site/cart.png" />
                                </a>
                                <a class="productdetailslink" href="asd">
                                    <div class="newFlag"></div>
                                    <img class="album-cover" src="../Content/Images/Photos/3.png" />
                                    <h1>
                                        Testowy obrazek
                                    </h1>
                                </a>
                            </article>
                        </li>
                    </ul>
            </section>

                <section>
                    <ul class="ThreeColumnsCoversList large-cover-list">
                        <li>
                            <article>
                                <a class="addtocartlink" href="aaaa">
                                    <img src="../Content/Images/Site/cart.png" />
                                </a>
                                <a class="productdetailslink" href="asd">
                                    <div class="bestsellerFlag"></div>
                                    <img class="album-cover" src="../Content/Images/Photos/1.png" />
                                    <h1>
                                        Testowy obrazek
                                    </h1>
                                </a>
                            </article>
                        </li>
                        <li>
                            <article>
                                <a class="addtocartlink" href="aaaa">
                                    <img src="../Content/Images/Site/cart.png" />
                                </a>
                                <a class="productdetailslink" href="asd">
                                    <div class="bestsellerFlag"></div>
                                    <img class="album-cover" src="../Content/Images/Photos/2.png" />
                                    <h1>
                                        Testowy obrazek
                                    </h1>
                                </a>
                            </article>
                        </li>
                        <li>
                            <article>
                                <a class="addtocartlink" href="aaaa">
                                    <img src="../Content/Images/Site/cart.png" />
                                </a>
                                <a class="productdetailslink" href="asd">
                                    <div class="bestsellerFlag"></div>
                                    <img class="album-cover" src="../Content/Images/Photos/3.png" />
                                    <h1>
                                        Testowy obrazek
                                    </h1>
                                </a>
                            </article>
                        </li>
                    </ul>*@
</section>

@*<a href="">
        <img id="baner-main" src="../Content/Images/Site/baner-main.png" />
    </a>*@

WebAppMVC/WebAppMVC/Views/Home/Newsletter.cshtml
@{
    ViewBag.Title = "Newsletter";
    Layout = "~/Views/_Layout.cshtml";
}

<h2>Newsletter</h2>

WebAppMVC/WebAppMVC/Views/Home/PrivacyPolicy.cshtml
@{
    ViewBag.Title = "PrivacyPolicy";
    Layout = "~/Views/_Layout.cshtml";
}

<h2>PrivacyPolicy</h2>

WebAppMVC/WebAppMVC/Views/Home/SizeGuide.cshtml
@{
    ViewBag.Title = "SizeGuide";
    Layout = "~/Views/_Layout.cshtml";
}

<h2>SizeGuide</h2>

WebAppMVC/WebAppMVC/Views/_Layout.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
        <meta name="viewport" content="width=device-width" />
        <title>@ViewBag.Title</title>
    <link href="@Url.Content("~/Content/CSS/HTMLPrototype.css")" rel="stylesheet" />
</head>
<body>
<header>
    <div style="overflow: hidden;">
        <a id="facebook-header" href="http://www.ikea.com/pl">
            REAL IKEA WEBSITE
        </a>
        <a id="cart-header-link" href="">
            CART (0)
            <span></span>
        </a>
    </div>
    <a id="main-header-logo" href="@Url.Content("~/")">
        <img src="@Url.Content("~/Content/Images/Site/logo-main.png")" class="center" alt=""/>
    </a>
</header>
<div>
    @RenderBody()
</div>
<footer>
    <nav>
        <ul>
            <li><a href="@Url.Content("~/")">Home</a></li>
            <li><a href="@Url.Action("StaticContent", "Home", new {viewname = "about"})">About</a></li>
            <li><a href="@Url.Action("StaticContent", "Home", new {viewname = "contact"})">Contact</a></li>
            <li><a href="@Url.Action("StaticContent", "Home", new {viewname = "newsletter"})">Newsletter</a></li>
            <li><a href="@Url.Action("StaticContent", "Home", new {viewname = "privacypolicy"})">Privacy Policy</a></li>
            <li><a href="@Url.Action("StaticContent", "Home", new {viewname = "sizeguide"})">Size Guide</a></li>
        </ul>
    </nav>
    <div id="footer-cd-logo">
        <img src="@Url.Content("~/Content/Images/Site/footer-cd.png")" alt=""/>
    </div>
    <div id="footer-copyright">
        Copyright &copy; 2017 Krystian Trubisz
    </div>
</footer>
    @RenderSection("ScriptsBottom", required:false)
</body>
</html>